[package]
name = "b"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
reqwest = { version = "0.11", features = ["blocking", "json"] }
clap = "2.33"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
mio = "0.6"
